-- All test records and queued notifications roll back. No email is sent.
begin;
do $$
declare parent uuid:=gen_random_uuid(); reviewer uuid:=gen_random_uuid(); treasurer uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); rid uuid:=gen_random_uuid(); p jsonb; r jsonb; count_rows integer;
begin
 insert into auth.users(id,phone,phone_confirmed_at) values(parent,'+15005550101',now()),(reviewer,'+15005550102',now()),(treasurer,'+15005550103',now()),(outsider,'+15005550104',now());
 insert into public.cr_staff(email,name,role) values('+15005550102','Test Reviewer','approver'),('+15005550103','Test Treasurer','treasurer');
 perform set_config('request.jwt.claim.sub',parent::text,true);
 p:=jsonb_build_object('id',rid,'requester_name','Test Parent','phone','4045550123','payee','Test Parent','delivery','pickup','committee','General RCAP','purpose','Supplies for an RCAP event','acknowledged',true,'approver_email','+15005550102','total_cents',1,'items',jsonb_build_array(jsonb_build_object('date',current_date::text,'description','Test expense','amount_cents',1250,'receipts','[]'::jsonb)));
 begin perform public.cr_action('submit',p);raise exception 'TEST missing receipts passed';exception when others then if sqlerrm not like '%Attach 1 to 5 receipts%' then raise;end if;end;
 p:=jsonb_set(p,'{items,0,receipts}',jsonb_build_array(jsonb_build_object('path',parent::text||'/'||rid::text||'/receipt.pdf','name','receipt.pdf')));
 begin perform public.cr_action('submit',p);raise exception 'TEST missing upload passed';exception when others then if sqlerrm not like '%not finished uploading%' then raise;end if;end;
 insert into storage.objects(bucket_id,name,metadata) values('check-receipts',parent::text||'/'||rid::text||'/receipt.pdf','{"size":100,"mimetype":"application/pdf"}');
 p:=p||jsonb_build_object('delivery','zelle','zelle_contact','invalid');
 begin perform public.cr_action('submit',p);raise exception 'TEST invalid Zelle passed';exception when others then if sqlerrm not like '%registered with Zelle%' then raise;end if;end;
 p:=p||jsonb_build_object('zelle_contact','parent@example.test','archive_email','parent@example.test');
 r:=public.cr_action('submit',p);
 if (select count(*) from public.cr_notifications where request_id=rid and archive_snapshot is not null)<>2 then raise exception 'TEST archive copies missing';end if;
 if r->>'zelle_contact'<>'parent@example.test' then raise exception 'TEST Zelle recipient not saved';end if;
 if r->>'status'<>'submitted' or (r->>'total_cents')::int<>1250 then raise exception 'TEST total/status failed';end if;
 if (select count(*) from public.cr_notifications where request_id=rid and channel='sms')<2 then raise exception 'TEST notifications missing';end if;
 perform public.cr_action('submit',p);
 if (select count(*) from public.cr_history where request_id=rid)<>1 then raise exception 'TEST duplicate submission';end if;
 begin perform public.cr_action('approved',jsonb_build_object('id',rid,'version',1));raise exception 'TEST self review passed';exception when others then if sqlerrm not like '%own request%' then raise;end if;end;
 begin perform public.cr_action('staff','{"email":"intruder@example.test","name":"Intruder","role":"secretary"}');raise exception 'TEST escalation passed';exception when others then if sqlerrm not like '%Secretary access%' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',outsider::text,true);
 set local role authenticated;
 select count(*) into count_rows from public.cr_requests where id=rid;
 if count_rows<>0 then raise exception 'TEST request leaked';end if;
 select count(*) into count_rows from storage.objects where bucket_id='check-receipts' and name=parent::text||'/'||rid::text||'/receipt.pdf';
 if count_rows<>0 then raise exception 'TEST receipt leaked';end if;
 begin update public.cr_requests set status='approved' where id=rid;raise exception 'TEST direct write passed';exception when insufficient_privilege then null;end;
 reset role;
 perform set_config('request.jwt.claim.sub',reviewer::text,true);
 set local role authenticated;
 select count(*) into count_rows from public.cr_requests where id=rid;
 if count_rows<>1 then raise exception 'TEST reviewer cannot read';end if;
 select count(*) into count_rows from storage.objects where bucket_id='check-receipts' and name=parent::text||'/'||rid::text||'/receipt.pdf';
 if count_rows<>1 then raise exception 'TEST reviewer cannot read receipt';end if;
 r:=public.cr_action('needs_changes',jsonb_build_object('id',rid,'version',1,'note','Please clarify the purpose.'));
 reset role;
 perform set_config('request.jwt.claim.sub',parent::text,true);
 p:=p||jsonb_build_object('version',2,'purpose','Updated purpose with additional detail');
 r:=public.cr_action('submit',p);
 if r->>'status'<>'submitted' or (r->>'version')::int<>3 then raise exception 'TEST resubmission failed';end if;
 perform set_config('request.jwt.claim.sub',treasurer::text,true);
 begin perform public.cr_action('paid',jsonb_build_object('id',rid,'version',3,'payment_date',current_date,'payment_reference','TEST'));raise exception 'TEST payment before approval';exception when others then if sqlerrm not like '%approval is required%' then raise;end if;end;
 begin perform public.cr_action('approved',jsonb_build_object('id',rid,'version',3));raise exception 'TEST unassigned approval';exception when others then if sqlerrm not like '%assigned board member%' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',reviewer::text,true);
 r:=public.cr_action('approved',jsonb_build_object('id',rid,'version',3,'note','Receipts reviewed.'));
 begin perform public.cr_action('approved',jsonb_build_object('id',rid,'version',3));raise exception 'TEST stale update';exception when others then if sqlerrm not like '%changed. Refresh%' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',treasurer::text,true);
 r:=public.cr_action('paid',jsonb_build_object('id',rid,'version',4,'payment_date',current_date,'payment_reference','TEST-123'));
 if r->>'status'<>'paid' then raise exception 'TEST payment not recorded';end if;
 if (select count(*) from public.cr_history where request_id=rid)<>5 then raise exception 'TEST history incomplete';end if;
 if (select count(*) from public.cr_notifications where request_id=rid and archive_snapshot is not null)<>10 then raise exception 'TEST archive history copies missing';end if;
 if not exists(select 1 from public.cr_notifications where request_id=rid and archive_snapshot->'event'->>'action'='submitted' and archive_snapshot->'request'->>'purpose'='Supplies for an RCAP event') then raise exception 'TEST original snapshot overwritten';end if;
 if not exists(select 1 from public.cr_notifications where request_id=rid and archive_snapshot->'request'->>'payment_reference'='TEST-123') then raise exception 'TEST payment absent from archive';end if;
 raise notice 'PASS: receipt gates, exact totals, idempotency, self-review, escalation, private records and receipts, correction, assigned approval, stale updates, payment gating, audit and notification queue';
end $$;
rollback;
select 'Phone sign-in, Zelle, and finance workflow and access tests passed; test records rolled back.' as result;
