import { lazy, Suspense, useEffect, useState } from 'react';
import { ArrowUpRight, Camera, Check, Heart, Luggage, MessageCircle, Plane, Trash2 } from 'lucide-react';
const Upload = lazy(() => import('../london/App.jsx').then(module => ({ default: module.Upload })));
import * as db from '../london/data.js';
import { PREP } from '../london/config.js';
import '../london/london.css';
import './ready.css';
const IDEAS = [
  { id: 'packing-bags', title: 'The packing situation.', prompt: 'What’s going in your suitcase?', text: 'The essentials. The overpacking. The one thing they refuse to leave behind.', icon: Luggage, tag: 'SNAP A PHOTO' },
  { id: 'most-excited', title: 'The big anticipation.', prompt: 'What are you most excited to see or do?', text: 'Ask your traveler. Hit record. Let their excitement do the talking.', icon: MessageCircle, tag: 'ASK. RECORD. SHARE.' },
  { id: 'dreaming-of-london', title: 'The London predictions.', prompt: 'What do you think London will be like?', text: 'The food? The accents? The weather? Capture their predictions before the adventure.', icon: Plane, tag: 'SAVE THE BEFORE' },
];
export default function Ready() {
 const [events,setEvents]=useState([]), [profile,setProfile]=useState(db.localProfile), [upload,setUpload]=useState(null), [photos,setPhotos]=useState([]), [owner,setOwner]=useState(''), [error,setError]=useState(''), [notice,setNotice]=useState(''), [removing,setRemoving]=useState(''), [confirming,setConfirming]=useState('');
 async function refresh() { try {const [albums,images,me]=await Promise.all([db.listEvents(),db.listPhotos(),db.getOwner()]);setEvents(albums.filter(e=>e.slug===PREP.slug));setPhotos(images.filter(p=>p.eventId===albums.find(e=>e.slug===PREP.slug)?.id && p.owner===me));setOwner(me);setError('');} catch {setError('We couldn’t open sharing just yet. Please try again.');} }
 useEffect(()=>{refresh();},[]);
 async function remove(p) {setRemoving(p.id);try {await db.hidePhoto(p.id);await refresh();setConfirming('');}catch {setError('That moment could not be removed. Please try again.');}finally{setRemoving('');}}
 return <div className="ready"><header className="ready-header"><img src="/london/ron-clark-academy.png" alt="The Ron Clark Academy" width="520" height="120"/><span>CLASS OF 2028<br/><small>THE ADVENTURE STARTS HERE</small></span></header>
 <main><section className="ready-hero"><div><p className="ready-kicker">LONDON + PARIS · OCTOBER 11–17</p><h1>Before the flight.<br/>All the <em>feels.</em></h1><p className="ready-lead">RCA 2028, let’s capture the getting ready.</p><p>The bags are coming out. The excitement is getting real. Families, send a photo or a quick video of your traveler before the big adventure.</p><button className="l-button" onClick={()=>setUpload({})}><Camera size={19}/> Share your getting-ready moment <ArrowUpRight size={18}/></button><small>One photo. One question. A memory worth keeping.</small></div><div className="ready-art"><img src="/london/london-morning.jpg" alt="Morning light over Big Ben and Westminster Bridge"/><span className="ready-stamp">NEXT STOP<br/><b>LONDON</b><Plane size={25}/></span><div className="ready-note">The adventure starts<br/>before the airport. <Heart size={23}/></div></div></section>
 <section className="ready-ideas"><p className="ready-kicker">YOUR FIRST POSTCARD STARTS AT HOME</p><h2>Pick a moment. Make it yours.</h2><p>Take us into the excitement. A camera roll favorite or a quick answer on video is perfect.</p><div className="ready-cards">{IDEAS.map(({id,title,prompt,text,icon:Icon,tag},i)=><button key={id} onClick={()=>setUpload({inspiration:id,prompt})}><div><Icon size={28}/><span>0{i+1}</span></div><small>{tag}</small><h3>{title}</h3><blockquote>“{prompt}”</blockquote><p>{text}</p><b>Share this moment <ArrowUpRight size={17}/></b></button>)}</div></section>
 <section className="ready-memory"><Heart size={24}/><div><h2>Someday, this will be the “before.”</h2><p>Save the excitement now. These photos and videos will become part of our class’s London + Paris trip collection, right alongside the memories still to come.</p></div></section>
 {notice&&<p role="status" className="ready-notice"><Check size={18}/>{notice}</p>}{error&&<p role="alert" className="l-error">{error} <button className="l-text" onClick={refresh}>Try again</button></p>}
 {photos.length>0&&<section className="ready-mine" id="my-moments"><p className="ready-kicker">YOUR CONTRIBUTIONS</p><h2>Your first postcards.</h2><p>Thanks for starting the story. You can remove your uploads here on this device.</p><div className="ready-mine-grid">{photos.map(p=><article key={p.id}>{p.kind==='video'?<video controls playsInline preload="metadata" poster={db.mediaUrl(p)} src={db.mediaUrl(p,'orig')}/>:<img src={db.mediaUrl(p)} alt={p.caption||'Your getting-ready moment'}/>}<p>{p.caption||'Getting ready for London'}</p>{p.owner===owner&&<button className="l-text" disabled={removing===p.id} onClick={()=>confirming===p.id?remove(p):setConfirming(p.id)}><Trash2 size={15}/>{removing===p.id?'Removing…':confirming===p.id?'Confirm removal':'Remove my upload'}</button>}</article>)}</div></section>}
 </main><footer className="ready-footer"><b>RON CLARK ACADEMY · CLASS OF 2028</b><span>First postcards from home. Next stop, the world.</span></footer>
 {upload&&<Suspense fallback={<p role="status" className="ready-notice">Opening sharing…</p>}><Upload parentOnly events={events} initialAlbum={PREP.slug} initialPrompt={upload.prompt||''} initialInspiration={upload.inspiration||''} profile={profile} setProfile={setProfile} close={()=>setUpload(null)} done={()=>{refresh();setNotice('Your first postcard is part of the story. Thank you!');}} viewUploads={()=>{setUpload(null);document.getElementById('my-moments')?.scrollIntoView({behavior:'smooth'});}}/></Suspense>}</div>;
}
