import {describe,it,expect,vi,afterEach} from 'vitest';
import sync from './sync.js';
const response=()=>({setHeader:vi.fn(),status:vi.fn().mockReturnThis(),json:vi.fn().mockReturnThis()});
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});
describe('committee Drive sync boundary',()=>{
 it('rejects unsigned requests before contacting services',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);const res=response();await sync({headers:{},body:{committee:'marcom'}},res);expect(res.status).toHaveBeenCalledWith(400);expect(fetch).not.toHaveBeenCalled();});
 it('checks membership before contacting the owner-authorized updater',async()=>{const fetch=vi.fn().mockResolvedValue({ok:false});vi.stubGlobal('fetch',fetch);vi.stubEnv('PLAYBOOK_DRIVE_WEBHOOK_URL','https://script.google.com/macros/s/test/exec');const res=response();await sync({headers:{authorization:'Bearer valid.jwt'},body:{committee:'men'}},res);expect(res.status).toHaveBeenCalledWith(403);expect(fetch).toHaveBeenCalledTimes(1);});
 it('never reports a database save as a successful Drive save when authorization is pending',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true}));vi.stubEnv('PLAYBOOK_DRIVE_WEBHOOK_URL','');const res=response();await sync({headers:{authorization:'Bearer valid.jwt'},body:{committee:'trunk'}},res);expect(res.status).toHaveBeenCalledWith(503);expect(res.json.mock.calls[0][0].ok).toBeUndefined();});
 it('rejects a substituted webhook host',async()=>{const fetch=vi.fn().mockResolvedValue({ok:true});vi.stubGlobal('fetch',fetch);vi.stubEnv('PLAYBOOK_DRIVE_WEBHOOK_URL','https://example.com/macros/s/test/exec');const res=response();await sync({headers:{authorization:'Bearer valid.jwt'},body:{committee:'men'}},res);expect(res.status).toHaveBeenCalledWith(502);expect(fetch).toHaveBeenCalledTimes(1);});
 it('only reports success after the updater confirms its write',async()=>{const fetch=vi.fn().mockResolvedValueOnce({ok:true}).mockResolvedValueOnce({ok:true,json:async()=>({ok:true,doc_url:'https://docs.google.com/document/d/record/edit',synced_at:'2026-10-09T18:00:00Z'})});vi.stubGlobal('fetch',fetch);vi.stubEnv('PLAYBOOK_DRIVE_WEBHOOK_URL','https://script.google.com/macros/s/test/exec');const res=response();await sync({headers:{authorization:'Bearer valid.jwt'},body:{committee:'men',doc_id:'arbitrary',content:'untrusted'}},res);expect(res.status).toHaveBeenCalledWith(200);const sent=JSON.parse(fetch.mock.calls[1][1].body);expect(sent.doc_id).toBeUndefined();expect(sent.content).toBeUndefined();expect(sent.committee).toBe('men');});
});
