import React,{act} from 'react';
import {createRoot} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
vi.mock('./data.js',()=>({client:{auth:{getSession:vi.fn(),signInWithOtp:vi.fn(),verifyOtp:vi.fn(),updateUser:vi.fn()}},syncAccount:vi.fn(),signOutAccount:vi.fn()}));
import {client,syncAccount} from './data.js';
import {LoginPanel,normalizePhone} from './LoginGate.jsx';
let root,host,ready;
beforeEach(async()=>{globalThis.IS_REACT_ACT_ENVIRONMENT=true;vi.clearAllMocks();client.auth.getSession.mockResolvedValue({data:{session:null}});client.auth.signInWithOtp.mockResolvedValue({error:null});client.auth.verifyOtp.mockResolvedValue({data:{user:{id:'person',phone:'+14045550123'}},error:null});client.auth.updateUser.mockResolvedValue({error:null});syncAccount.mockResolvedValue({user:{id:'person'}});ready=vi.fn();host=document.createElement('div');document.body.append(host);root=createRoot(host);await act(async()=>root.render(<LoginPanel onReady={ready}/>));});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();});
async function input(value){await act(async()=>{const field=host.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(field,value);field.dispatchEvent(new Event('input',{bubbles:true}));});}
async function submit(){await act(async()=>host.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));}
it('normalizes US and international phone numbers without guessing incomplete numbers',()=>{expect(normalizePhone('(404) 555-0123')).toBe('+14045550123');expect(normalizePhone('+44 7700 900123')).toBe('+447700900123');expect(()=>normalizePhone('123')).toThrow();});
it('verifies SMS before attaching an email backup to the same account',async()=>{await input('4045550123');await submit();expect(client.auth.signInWithOtp).toHaveBeenCalledWith({phone:'+14045550123',options:{channel:'sms'}});await input('123456');await submit();expect(client.auth.verifyOtp).toHaveBeenCalledWith({phone:'+14045550123',token:'123456',type:'sms'});expect(syncAccount).toHaveBeenCalled();expect(host.textContent).toContain('Add your backup email');await input('parent@example.com');await submit();expect(client.auth.updateUser).toHaveBeenCalledWith({email:'parent@example.com'});expect(client.auth.signInWithOtp).toHaveBeenCalledTimes(1);await input('654321');await submit();expect(client.auth.verifyOtp).toHaveBeenLastCalledWith({email:'parent@example.com',token:'654321',type:'email_change'});expect(ready).toHaveBeenCalledTimes(1);});
it('backup email sign-in does not create a second account',async()=>{await act(async()=>host.querySelector('.l-text').click());await input('parent@example.com');await submit();expect(client.auth.signInWithOtp).toHaveBeenCalledWith({email:'parent@example.com',options:{shouldCreateUser:false,emailRedirectTo:expect.any(String)}});});
it('keeps failed verification out of the contribution form',async()=>{await input('4045550123');await submit();client.auth.verifyOtp.mockResolvedValue({error:{message:'Code expired'}});await input('123456');await submit();expect(host.querySelector('[role=alert]').textContent).toBe('Code expired');expect(ready).not.toHaveBeenCalled();expect(syncAccount).not.toHaveBeenCalled();});
