import { MapPin } from 'lucide-react';
// Coastlines: Natural Earth 1:50m admin countries, public domain.
import land from './map-land.json';
const STOPS = [
  { name: 'London', lon: -.1276, lat: 51.5072, album: 'hello-london', days: ['hello-london', 'history-and-six'], labelX: 401, labelY: 137 },
  { name: 'Hampton Court', lon: -.3378, lat: 51.4036, album: 'palaces-and-stones', days: ['palaces-and-stones'], labelX: 361, labelY: 117, anchor: 'end' },
  { name: 'Stonehenge', lon: -1.8262, lat: 51.1789, album: 'palaces-and-stones', days: ['palaces-and-stones'], labelX: 266, labelY: 194, anchor: 'end' },
  { name: 'Paris', lon: 2.3522, lat: 48.8566, album: 'bonjour-paris', days: ['bonjour-paris', 'a-day-to-remember', 'home-with-stories'], labelX: 537, labelY: 307 },
  { name: 'Versailles', lon: 2.1204, lat: 48.8049, album: 'a-day-to-remember', days: ['a-day-to-remember'], labelX: 485, labelY: 346, anchor: 'end' },
];
const point = (stop) => [(stop.lon + 7) * 55, (54 - stop.lat) * 61];
export default function TripMap({ chapter, pickAlbum }) {
  const active = STOPS.filter((stop) => stop.days.includes(chapter.day.slug));
  return <section className="l-route" aria-labelledby="trip-route-title"><div className="l-route-copy"><p className="l-eyebrow"><MapPin size={15} /> THE POSTCARD ROUTE</p><h2 id="trip-route-title">A little further. <br />A little more wonder.</h2><p>London streets, ancient stones, then across the Channel to Paris. One class collecting stories along the way.</p><div className="l-route-day"><span>{chapter.label}</span><b>{active.length ? active.map((stop) => stop.name).join(' + ') : 'Atlanta → London → Paris → home'}</b></div><p className="l-small">Tap a place to explore its day.</p></div><div className="l-route-map"><svg viewBox="0 0 760 420" role="img" aria-label="Trip route through southern England and northern France: London, Hampton Court, Stonehenge, Paris and Versailles"><defs><pattern id="route-grid" width="36" height="36" patternUnits="userSpaceOnUse"><path d="M 36 0 L 0 0 0 36" fill="none" stroke="#1a2a56" strokeOpacity=".05" /></pattern></defs><rect width="760" height="420" fill="#edf1f5" /><rect width="760" height="420" fill="url(#route-grid)" />{land.map((shape, i) => <path key={i} d={shape.d} fill="#faf8f2" stroke="#cbd2d9" strokeWidth="1.2" />)}<text x="255" y="65" className="l-country">ENGLAND</text><text x="600" y="388" className="l-country">FRANCE</text><text x="325" y="273" className="l-channel" transform="rotate(-20 325 273)">The English Channel</text><path d="M286 172 Q325 137 366 158 L378 152 Q434 199 464 253 Q487 282 514 314 L502 317" className="l-map-route" /><text x="450" y="211" className="l-map-train">To Paris by train</text>{STOPS.map((stop) => { const [x, y] = point(stop); const selected = stop.days.includes(chapter.day.slug); return <g key={stop.name} className={selected ? 'l-map-stop active' : 'l-map-stop'}><circle cx={x} cy={y} r={selected ? 12 : 8} fill={selected ? '#f0b323' : '#1a2a56'} stroke="#faf8f2" strokeWidth="3" /><circle cx={x} cy={y} r="2.5" fill={selected ? '#1a2a56' : '#faf8f2'} /><text x={stop.labelX} y={stop.labelY} textAnchor={stop.anchor || 'start'}>{stop.name}</text>{stop.name === 'Hampton Court' && <path d={`M${x} ${y-10} L${x-3} 124`} fill="none" stroke="#9ba8bd" />}</g>; })}</svg><div className="l-route-places" aria-label="Explore the trip stops">{STOPS.map((stop) => <button key={stop.name} className={stop.days.includes(chapter.day.slug) ? 'active' : ''} onClick={() => pickAlbum(stop.album)} aria-pressed={stop.days.includes(chapter.day.slug)} aria-label={`Explore ${stop.name}`}>{stop.name}</button>)}</div><small>Illustrated connections, not exact travel paths. Map: <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth</a></small></div></section>;
}
